# Generated by Django 3.2.4 on 2021-06-24 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Zal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.IntegerField(default=20, verbose_name='Количество мест')),
            ],
        ),
        migrations.CreateModel(
            name='Seans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('ticket_amount', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=10, max_digits=2)),
                ('film', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zal.film')),
                ('zal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zal.zal')),
            ],
        ),
    ]
