# Generated by Django 3.2.4 on 2021-06-23 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Zal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount_mest', models.IntegerField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name='Seans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('mesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zal.mesto')),
                ('zal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zal.zal')),
            ],
        ),
        migrations.AddField(
            model_name='mesto',
            name='zal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zal.zal'),
        ),
    ]
