# Generated by Django 3.2.4 on 2021-06-26 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seans',
            old_name='date_end',
            new_name='datetime_end',
        ),
        migrations.RenameField(
            model_name='seans',
            old_name='date_start',
            new_name='datetime_start',
        ),
        migrations.RemoveField(
            model_name='seans',
            name='ticket_amount',
        ),
    ]
