# Generated by Django 3.2.4 on 2021-06-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seans',
            name='mesto',
        ),
        migrations.RemoveField(
            model_name='zal',
            name='amount_mest',
        ),
        migrations.AddField(
            model_name='zal',
            name='size',
            field=models.IntegerField(default=20, verbose_name='Количество мест'),
        ),
        migrations.DeleteModel(
            name='Mesto',
        ),
    ]
