# Generated by Django 3.2.4 on 2021-06-26 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zal', '0002_auto_20210626_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seans',
            name='price',
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seans', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='zal.seans')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
