# Generated by Django 3.2.4 on 2021-06-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zal', '0005_auto_20210626_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seans',
            name='date_end',
            field=models.DateField(default=0),
        ),
        migrations.AlterField(
            model_name='seans',
            name='date_start',
            field=models.DateField(default=0),
        ),
        migrations.AlterField(
            model_name='seans',
            name='time_end',
            field=models.TimeField(default=0),
        ),
        migrations.AlterField(
            model_name='seans',
            name='time_start',
            field=models.TimeField(default=0),
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
