# Generated by Django 3.2.4 on 2021-07-07 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zal', '0006_auto_20210630_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeansGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(default=0)),
                ('date_end', models.DateField(default=0)),
                ('time_start', models.TimeField(default=0)),
                ('time_end', models.TimeField(default=0)),
                ('price', models.IntegerField(default=10)),
                ('film', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zal.film')),
                ('zal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zal.zal')),
            ],
        ),
        migrations.AddField(
            model_name='seans',
            name='seans_group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='zal.seansgroup'),
            preserve_default=False,
        ),
    ]
