# Generated by Django 3.2.4 on 2021-07-08 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zal', '0007_auto_20210708_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seans',
            name='seans_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seanses', to='zal.seansgroup'),
        ),
    ]
