# Generated by Django 3.2.4 on 2021-07-02 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zal', '0006_auto_20210630_1512'),
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='seans',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zal.seans'),
        ),
    ]
