# Generated by Django 3.2.4 on 2021-07-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_alter_ticket_seans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='amount',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
