# Generated by Django 3.2.4 on 2021-07-07 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zal', '0007_auto_20210708_0055'),
        ('ticket', '0003_alter_ticket_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='seans',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='zal.seansgroup'),
        ),
    ]
